### ISSUE TITLE
Discussion on finding a working solution for Spring Data and Elasticsearch 5.x.x and 6.x.x

### ISSUE THREAD

**Issue by FlatsWire-Niko** [CGavrila/spring-data-elasticsearch#1]
Hello,

Sorry to bother you by making an issue. I don't know how to contact you in Github.
Have you found any solution on this ES issue ?

I'm facing the same and I spent 2h searching the Internet for a solution. Without success.
So I've switched back to 2.0.4 which work well.
I'm trying to setup a project with version 5.5.0 of ES.

I've tried any combinaisons of version without success...

Kind regards,
Nicolas

**Comment by CGavrila** [comment]
Hi Nicolas!

No problem with you contacting me.

Unfortunately, I could not find any solution. After spending many days on this, I decided it's just not worth it and did the same thing as you, which is switching back to 2.x.x. Not sure where you found this repo, but I created it as part of this topic in the ES forum - https://discuss.elastic.co/t/errors-when-using-spring-data-elasticsearch-version-3-0-0-build-snapshot-and-elasticsearch-5-4-0/90525. Maybe there's something there that can help you.

Good luck!

**Comment by FlatsWire-Niko** [comment]
Hi Cristian,


Thanks a lot for your feedback. I’ve found your repo from the link you pasted in your email.
If I find something later I’ll drop you an email!


Thanks again and good luck!
Nicolas

**Comment by rfanjul** [comment]
I also have the same issue - No solution for the moment

**Comment by CGavrila** [comment]
Thanks @rfanjul for the comment. Just saw it, sorry!

I have recently tried again and I didn't get anywhere.

@rfanjul @FlatsWire-Niko I have also opened this issue in their official Jira board - https://jira.spring.io/browse/DATAES-364. There has been no reply, but if more people report/flag this in some way, maybe there's a chance.

**Comment by mansoor67890** [comment]
Try excluding ElasticsearchDataAutoConfiguration. i.e.
@SpringBootApplication(exclude=ElasticsearchDataAutoConfiguration.class).
I did this, now my project is working.

**Comment by CGavrila** [comment]
Thanks for the suggestion @mansoor67890, will try and leave a comment here.

**Comment by CGavrila** [comment]
@mansoor67890 Again, thanks for the suggestion!

I tried that, but I need to replace the stuff in `ElasticsearchDataAutoConfiguration.class` with other `@Bean`s. Did you do that manually?

**Comment by mansoor67890** [comment]
No, 
@CGavrila I did this only:
@springbootapplication(exclude=ElasticsearchDataAutoConfiguration.class).

**Comment by CGavrila** [comment]
@mansoor67890 I tried that too, but then Spring immediately complained about `elasticsearchTemplate` missing, so there must be something else in your case that creates the `elasticsearchTemplate` `@Bean` and anything else that is missing.

**Comment by CGavrila** [comment]
Ping @FlatsWire-Niko @rfanjul 

I managed to get it working with Elasticsearch 5.5.3. I've tried with the new 6.0.0, but wasn't able to get it working.

My `pom.xml` file looks a bit like:
```
         <parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.0.0.M6</version> <======================= (latest version)
		<relativePath/>
	</parent>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>1.8</java.version>
		<elasticsearch.version>5.5.0</elasticsearch.version> <=======================
	</properties>

	<dependencies>

		<!-- Spring -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-elasticsearch</artifactId>
		</dependency>  <======================= (no version in here)
               .......
	</dependencies> 
``` 

I also run my ES via Docker compose:
```
version: '2'
services:
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.3
    container_name: elasticsearch
    environment:
      - cluster.name=local
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    ports:
      - 9200:9200
      - 9300:9300
```

Hope this helps someone else.
